//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.PostgreSql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.PostgreSql.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT column_name, column_default, is_nullable, character_maximum_length,
        ///       CASE WHEN data_type=&apos;USER-DEFINED&apos; THEN udt_name ELSE trim(both &apos;\&quot;&apos; from data_type) END AS data_type
        ///FROM information_schema.columns
        ///WHERE table_schema=&apos;{0}&apos;
        ///  AND table_name=&apos;{1}&apos;.
        /// </summary>
        internal static string ColumnsQuery {
            get {
                return ResourceManager.GetString("ColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT rc.constraint_name,
        ///       fkcu.table_schema, fkcu.table_name, fkcu.column_name, 
        ///       pkcu.table_schema AS master_table_schema, pkcu.table_name AS master_table_name, pkcu.column_name AS master_column_name
        ///FROM information_schema.referential_constraints rc
        ///JOIN information_schema.key_column_usage fkcu ON rc.constraint_name = fkcu.constraint_name
        ///JOIN information_schema.key_column_usage pkcu ON rc.unique_constraint_name = pkcu.constraint_name
        ///WHERE fkcu.ordinal_position = pkcu.ordinal_position [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignKeysQuery {
            get {
                return ResourceManager.GetString("ForeignKeysQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT kcu.column_name 
        ///FROM information_schema.table_constraints as tc
        ///JOIN information_schema.key_column_usage as kcu
        ///  ON kcu.constraint_schema = tc.constraint_schema
        /// AND kcu.constraint_name = tc.constraint_name
        /// AND kcu.table_schema = tc.table_schema
        /// AND kcu.table_name = tc.table_name
        /// WHERE tc.constraint_type = &apos;PRIMARY KEY&apos;
        ///   AND tc.table_schema = &apos;{0}&apos;
        ///   AND tc.table_name = &apos;{1}&apos;.
        /// </summary>
        internal static string PrimaryKeyQuery {
            get {
                return ResourceManager.GetString("PrimaryKeyQuery", resourceCulture);
            }
        }
    }
}
