//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.PostgreSql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.PostgreSql.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.column_name, c.column_default, c.is_nullable, c.data_type, c.character_maximum_length AS maximum_length, 
        ///       e.data_type AS element_type, e.character_maximum_length AS element_maximum_length
        ///FROM information_schema.columns c 
        ///LEFT JOIN information_schema.element_types e
        ///     ON ((c.table_catalog, c.table_schema, c.table_name, c.dtd_identifier)
        ///       = (e.object_catalog, e.object_schema, e.object_name, e.collection_type_identifier))
        ///WHERE c.table_schema = &apos;{0}&apos; AND c.table_name = &apos;{1}&apos;
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnsQuery {
            get {
                return ResourceManager.GetString("ColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT rc.constraint_name,
        ///       fkcu.table_schema, fkcu.table_name, fkcu.column_name, 
        ///       pkcu.table_schema AS master_table_schema, pkcu.table_name AS master_table_name, pkcu.column_name AS master_column_name
        ///FROM information_schema.referential_constraints rc
        ///JOIN information_schema.key_column_usage fkcu ON rc.constraint_name = fkcu.constraint_name
        ///JOIN information_schema.key_column_usage pkcu ON rc.unique_constraint_name = pkcu.constraint_name
        ///WHERE fkcu.ordinal_position = pkcu.ordinal_position [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignKeysQuery {
            get {
                return ResourceManager.GetString("ForeignKeysQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT u.*
        ///FROM (
        ///(SELECT r.specific_schema, r.specific_name, null AS parameter_name, 0 AS ordinal_position, r.data_type, null AS maximum_length,
        ///       &apos;RETURN&apos; AS parameter_mode, e.data_type AS element_data_type
        /// FROM information_schema.routines r
        /// LEFT JOIN information_schema.element_types e
        ///      ON ((r.specific_catalog, r.specific_schema, r.specific_name, r.dtd_identifier)
        ///        = (e.object_catalog, e.object_schema, e.object_name, e.collection_type_identifier))
        /// WHERE r.data_type != &apos;void&apos;) 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParametersQuery {
            get {
                return ResourceManager.GetString("ParametersQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT kcu.column_name 
        ///FROM information_schema.table_constraints as tc
        ///JOIN information_schema.key_column_usage as kcu
        ///  ON kcu.constraint_schema = tc.constraint_schema
        /// AND kcu.constraint_name = tc.constraint_name
        /// AND kcu.table_schema = tc.table_schema
        /// AND kcu.table_name = tc.table_name
        /// WHERE tc.constraint_type = &apos;PRIMARY KEY&apos;
        ///   AND tc.table_schema = &apos;{0}&apos;
        ///   AND tc.table_name = &apos;{1}&apos;.
        /// </summary>
        internal static string PrimaryKeyQuery {
            get {
                return ResourceManager.GetString("PrimaryKeyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT routine_name, specific_name, routine_schema 
        ///FROM information_schema.routines.
        /// </summary>
        internal static string StoredProceduresQuery {
            get {
                return ResourceManager.GetString("StoredProceduresQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT table_name, table_schema, table_type 
        ///FROM information_schema.tables
        ///.
        /// </summary>
        internal static string TablesQuery {
            get {
                return ResourceManager.GetString("TablesQuery", resourceCulture);
            }
        }
    }
}
